gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
#      ingress:
#        className: nginx-internal
#        enabled: true
#        hosts:
#          - local7-runtime.rnd-sandbox.cf-infra.com
      name: local7
      ingressUrl: "https://andriicf-ingresshost.ngrok.io"
  installer:
    skipValidation: true
  tunnel-client:
    enabled: false
