gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
#      ingress:
#        className: nginx-internal
#        enabled: true
#        hosts:
#          - local7-runtime.rnd-sandbox.cf-infra.com
      name: local7
      ingressUrl: "https://andriicf-ingresshost.ngrok.io"
  installer:
    skipValidation: true
  tunnel-client:
    enabled: false

  argo-cd:
    server:
      service:
        type: LoadBalancer
      replicas: 1
#      image:
#        repository: "andriicodefresh/argocd"
#        tag: "reporter"

    ## Application controller
    controller:
      # -- The number of application controller pods to run.
      # Additional replicas will cause sharding of managed clusters across number of replicas.
      replicas: 1
#      image:
#        repository: "andriicodefresh/argocd"
#        tag: "reporter"

    ## Repo Server
    repoServer:
      # -- The number of repo server pods to run
      replicas: 1
#      image:
#        repository: "andriicodefresh/argocd"
#        tag: "reporter"



    eventReporter:
      ## Amount of replicas for event reporting sharding
      replicas: 1
#      image:
#        repository: "andriicodefresh/argocd"
#        tag: "reporter-1"
      sourcesServer:
        enabled: false

    applicationVersioning:
      # -- enables the Codefresh application versioning feature
      enabled: true
      # -- use ApplicationConfiguration CRD to manage application versioning
      useApplicationConfiguration: true

#    event-reporters:
#      events:
#        argoCDServerServiceName: "0.tcp.eu.ngrok.io"
#        argoCDServerServicePort: "12558"
