gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io
  global:
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - https://andriicf-ingresshost.ngrok.io
      name: local7
  installer:
    skipValidation: true
