apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: kustomize-guestbook
spec:
  promotionTemplate:
    versionSource:
      file: kustomization.yaml
      jsonPath: $.images['4'].newTag
  concurrency: queue
