apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: version-product
spec:
  promotionTemplate:
    versionSource:
      file: versionSource.json
      jsonPath: $.parent.many[1].versionNumber
