apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-git-source
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/andrii-codefresh/codefresh-runtime_internal-shared-config.git
      path: git-sources/test01/default
      targetRevision: HEAD
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: test01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
