gitops-runtime:
  global:
    app-proxy:
      replicaCount: 0
      env:
        cors: >-
          http://local.codefresh.io,localhost:3017,http://andriicf-ingresshost.ngrok.io,http://andriicf-platform.ngrok.io
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
#      ingress:
#        className: nginx-internal
#        enabled: true
#        hosts:
#          - local55-runtime.rnd-sandbox.cf-infra.com
      name: local55
      ingressUrl: "https://andriicf-ingresshost.ngrok.io"
  installer:
    skipValidation: true
