gitops-runtime:
  app-proxy:
    replicaCount: 0
    config:
      cors: http://local.codefresh.io,https://andriicf-platform.ngrok.io
  global:
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        enabled: false
      ingressUrl: https://andriicf-ingresshost.ngrok.io
      name: local8
      isConfigurationRuntime: true
  installer:
    skipValidation: true
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
