apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secondary
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://gitlab.com/andrii9/git-source.git
      path: localx/secondary
      targetRevision: master
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: localx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
