kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    api_token: >-
      AgBzrtxesO4iQG1uNmVBhjue3f+jUhyw4GuSz/quEsI1GzgRkAT3+XJG92YxX3HSRH5PM5dSgj5BJ5hBIkN+sPpMfXOQexTAzNVO8NVIB4kMigcytNHON81fedK0wRJiugDMEABSGmfBVz+ChxgmaOEtqc3OzxxM+EiQiWbIwt/WgrPOwX0Zfql0o7ATE+1rWuUEH9iZHthf0tiafbzzmVSbIJ1yV8ZsffcBR5MyWVjehscjvfT6U7C+C8Hq1Dnx488xx4OVaum1bXrLzL9TOrSrQAmsufj92C8HaHGIXU+WKtmzhCJS0pFKmALmKMi9iCkSXGbJRh/LDPGIOlqn/5reTWs3Pgb+tsVuUMfFqAth1+JbA4HSmwooDPBjwKfqKUFBeA3nil4dycXqUCT7ChSWkjGoJLWb0Xw7m/7ExeX3gqH5Xq8rFVdaPxtKC5HodMQDPbw4IpLjEjTmlDz/6hUS6FN9Br2Cx33on0io7aLcfu3xX0jaZ+RMlj6A6P0+y61BTBix3nnlHpQPgPxCHG8w6MqVeU/96jA+ov+2eM02YN0T/ueeD0WpboHH8nZew204va8W6NhfnbyyGBv4nUbNPQd1Qmw5gPQOHT/8zIEHzUoK4wPc5ik/zcCq6wNkIPctcHZGekukuWuppVv/Un5t02jIk41IsJn3qGsa/SFmhRfOq8sLDY3EyZq8ibWtkg0SKGXpSltEOqchtO1NzXR/bwfKjuu6kgo=
