apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
    - list:
        elements:
          - name: app-1
            ns: ns-1
            cluster: in-cluster
          - name: app-2
            ns: ns-2
            cluster: in-cluster
          - name: app-3
            ns: ns-3
            cluster: in-cluster
          - name: app-4
            ns: ns-4
            cluster: in-cluster

          - name: app-0001
            ns: ns
            cluster: wrong-cluster
          - name: app-0002
            ns: ns
            cluster: wrong-cluster
          - name: app-0003
            ns: ns
            cluster: wrong-cluster
          - name: app-0004
            ns: ns
            cluster: wrong-cluster
          - name: app-0005
            ns: ns
            cluster: wrong-cluster
          - name: app-0006
            ns: ns
            cluster: wrong-cluster
          - name: app-0007
            ns: ns
            cluster: wrong-cluster
          - name: app-0008
            ns: ns
            cluster: wrong-cluster
          - name: app-0009
            ns: ns
            cluster: wrong-cluster
          - name: app-0010
            ns: ns
            cluster: wrong-cluster
  template:
    metadata:
      name: '{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        codefresh.io/product: version-product
      labels:
        abac: users
    spec:
      project: default
      destination:
        name: '{{cluster}}'
        namespace: '{{ns}}'
      source:
        path: helm-guestbook
        repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false