apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
    codefresh.io/runtime-health: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/andrii-codefresh/codefresh-runtime_internal-shared-config.git
    targetRevision: HEAD
    path: resources/local7/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: local7
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
