apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-gb-dep
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: version-product
spec:
  project: default
  destination:
    name: in-cluster
    namespace: gb
  source:
    path: helm-guestbook
    repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false