apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-gb-dep
spec:
  generators:
    - list:
        elements:
          - name: helm-gb-0001
            ns: gb
            cluster: wrong-cluster
          - name: helm-gb-0002
            ns: gb-1
            cluster: wrong-cluster
          - name: helm-gb-0003
            ns: gb-2
            cluster: wrong-cluster
          - name: helm-gb-0004
            ns: gb-3
            cluster: wrong-cluster
          - name: helm-gb-0005
            ns: gb-4
            cluster: wrong-cluster
          - name: helm-gb-0006
            ns: gb-5
            cluster: wrong-cluster
          - name: helm-gb-0007
            ns: gb-6
            cluster: wrong-cluster
          - name: helm-gb-0008
            ns: gb-7
            cluster: wrong-cluster
          - name: helm-gb-0009
            ns: gb-8
            cluster: wrong-cluster
          - name: helm-gb-0010
            ns: gb-9
            cluster: wrong-cluster
          - name: helm-gb-0011
            ns: gb-10
            cluster: wrong-cluster
          - name: helm-gb-0012
            ns: gb-11
            cluster: wrong-cluster
          - name: helm-gb-0013
            ns: gb-12
            cluster: wrong-cluster
          - name: helm-gb-0014
            ns: gb-14
            cluster: wrong-cluster
          - name: helm-gb-0015
            ns: gb-15
            cluster: wrong-cluster
          - name: helm-gb-0016
            ns: gb-16
            cluster: wrong-cluster
          - name: helm-gb-0017
            ns: gb-17
            cluster: wrong-cluster
          - name: helm-gb-0018
            ns: gb-17
            cluster: wrong-cluster
          - name: helm-gb-0019
            ns: gb-17
            cluster: wrong-cluster
          - name: helm-gb-0020
            ns: gb-17
            cluster: wrong-cluster
          - name: helm-gb-0021
            ns: gb-17
            cluster: wrong-cluster
          - name: helm-gb-0022
            ns: gb-17
            cluster: wrong-cluster
  template:
    metadata:
      name: '{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        codefresh.io/product: version-product
      labels:
        abac: users
    spec:
      project: default
      destination:
        name: '{{cluster}}'
        namespace: '{{ns}}'
      source:
        path: helm-guestbook
        repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false