apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-gb-dep
spec:
  generators:
    - list:
        elements:
          - name: helm-gb-0001
            ns: gb-0001
            cluster: in-cluster
          - name: helm-gb-0002
            ns: gb-0002
            cluster: in-cluster
          - name: helm-gb-0003
            ns: gb-0003
            cluster: in-cluster
          - name: helm-gb-0004
            ns: gb-0004
            cluster: in-cluster
          - name: helm-gb-0005
            ns: gb-0005
            cluster: in-cluster
          - name: helm-gb-0006
            ns: gb-0006
            cluster: in-cluster
          - name: helm-gb-0007
            ns: gb-0007
            cluster: in-cluster
          - name: helm-gb-0008
            ns: gb-0008
            cluster: in-cluster
          - name: helm-gb-0009
            ns: gb-0009
            cluster: in-cluster
          - name: helm-gb-0010
            ns: gb-0010
            cluster: in-cluster
          - name: helm-gb-0011
            ns: gb-0011
            cluster: in-cluster
          - name: helm-gb-0012
            ns: gb-0012
            cluster: in-cluster
          - name: helm-gb-0013
            ns: gb-0013
            cluster: in-cluster
          - name: helm-gb-0014
            ns: gb-0014
            cluster: in-cluster
          - name: helm-gb-0015
            ns: gb-0015
            cluster: in-cluster
          - name: helm-gb-0016
            ns: gb-0016
            cluster: in-cluster
          - name: helm-gb-0017
            ns: gb-0017
            cluster: in-cluster
          - name: helm-gb-0018
            ns: gb-0018
            cluster: in-cluster
          - name: helm-gb-0019
            ns: gb-0019
            cluster: in-cluster
          - name: helm-gb-0020
            ns: gb-0020
            cluster: in-cluster
  template:
    metadata:
      name: '{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        codefresh.io/product: version-product
      labels:
        abac: users
    spec:
      project: default
      destination:
        name: '{{cluster}}'
        namespace: '{{ns}}'
      source:
        path: helm-guestbook
        repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false