apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: local9
  labels:
    env: dev
spec:
  project: default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  source:
    repoURL: https://github.com/andrii-codefresh/argocd-example-apps1
    targetRevision: HEAD
    path: ./kustomize-guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: kustomize-guestbook

  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true