gitops-runtime:
  global:
    codefresh:
      accountId: 5b61a5a532fb5b0001d14a73
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: test-audit
