gitops-runtime:
  global:
    codefresh:
      url: "https://andriicf-platform.ngrok.io"
      accountId: 6365495094c7820be5a4544d
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: local52
      ingressUrl: "https://andriicf-ingresshost.ngrok.io"

  # -------------------------------------------------------------------------------------------------------------------------
  # Installer
  # -------------------------------------------------------------------------------------------------------------------------
  # -- Runtime installer used for running hooks and checks on the release
  installer:
    # -- if set to true, pre-install hook will *not* run
    skipValidation: true

  argo-cd:
    server:
      service:
        type: LoadBalancer
  event-reporters:
    events:
      argoCDServerServiceName: "0.tcp.eu.ngrok.io"
      argoCDServerServicePort: "14415"
  app-proxy:
    replicaCount: 0
#    config:
#      argoCdUrl: http://0.tcp.eu.ngrok.io:14415
  tunnel-client:
    enabled: false

## Application controller
controller:
  # -- The number of application controller pods to run.
  # Additional replicas will cause sharding of managed clusters across number of replicas.
  replicas: 0

## Server
server:
  # -- The number of server pods to run
  replicas: 0

## Repo Server
repoServer:
  # -- The number of repo server pods to run
  replicas: 0

eventReporter:
  ## Amount of replicas for event reporting sharding
  replicas: 0
