gitops-runtime:
  global:
    codefresh:
      url: "https://andriicf-platform.ngrok.io"
      accountId: 6365495094c7820be5a4544d
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: local52
      ingressUrl: "https://andriicf-ingresshost.ngrok.io"

  # -------------------------------------------------------------------------------------------------------------------------
  # Installer
  # -------------------------------------------------------------------------------------------------------------------------
  # -- Runtime installer used for running hooks and checks on the release
  installer:
    # -- if set to true, pre-install hook will *not* run
    skipValidation: true

  argo-cd:
    server:
      service:
        type: LoadBalancer
      replicas: 1
      image:
        tag: "v2.9-2024.3.12-b23aa3fb6"

    ## Application controller
    controller:
      # -- The number of application controller pods to run.
      # Additional replicas will cause sharding of managed clusters across number of replicas.
      replicas: 1
      image:
        tag: "v2.9-2024.3.12-b23aa3fb6"

    ## Repo Server
    repoServer:
      # -- The number of repo server pods to run
      replicas: 1
      image:
        tag: "v2.9-2024.3.12-b23aa3fb6"

    eventReporter:
      ## Amount of replicas for event reporting sharding
      replicas: 0

    applicationVersioning:
      # -- enables the Codefresh application versioning feature
      enabled: true
      # -- use ApplicationConfiguration CRD to manage application versioning
      useApplicationConfiguration: true

#  event-reporters:
#    events:
#      argoCDServerServiceName: "4.tcp.eu.ngrok.io"
#      argoCDServerServicePort: "13252"
  app-proxy:
    replicaCount: 0
#    config:
#      argoCdUrl: http://4.tcp.eu.ngrok.io:13252
  tunnel-client:
    enabled: false
