gitops-runtime:
  global:
    codefresh:
      url: "https://andriicf-platform.ngrok.io"
      accountId: 6365495094c7820be5a4544d
      userToken: 
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: local52
  argo-cd:
    server:
      service:
        type: LoadBalancer
