gitops-runtime:
  global:
    codefresh:
      url: "http://andriicf-platform.ngrok.io"
      accountId: 6365495094c7820be5a4544d
      userToken: 
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: local52
      ingressUrl: "http://andriicf-ingresshost.ngrok.io"
  argo-cd:
    server:
      service:
        type: LoadBalancer
  event-reporters:
   events:
     argoCDServerServiceName: "7.tcp.eu.ngrok.io"
     argoCDServerServicePort: "14365"
  app-proxy:
    config:
      argoCdUrl: http://7.tcp.eu.ngrok.io:14365
  tunnel-client:
    enabled: false
