gitops-runtime:
  global:
    codefresh:
      accountId: 5b61a5a532fb5b0001d14a73
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: test-audit
  #-----------------------------------------------------------------------------------------------------------------------
  # app-proxy
  #-----------------------------------------------------------------------------------------------------------------------
  app-proxy:
    image:
      repository: quay.io/codefresh/cap-app-proxy
      tag: 1.2566.1
  
    initContainer:
      image:
        repository: quay.io/codefresh/cap-app-proxy-init
        tag: 1.2566.1
