apiVersion: v1
kind: Service
metadata:
  name: {{ include "ga-arena-nginx.fullname" . }}
  labels:
    {{- include "ga-arena-nginx.labels" . | nindent 4 }}
    app-index: {{ include "ga-arena-nginx.appIndex" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ga-arena-nginx.selectorLabels" . | nindent 4 }}