gitops-runtime:
  app-proxy:
    image:
      tag: 1.3446.0
    config:
      cors: http://local.codefresh.io,https://andriicf-platform.ngrok.io
  global:
    codefresh:
      accountId: 6365495094c7820be5a4544d
      url: https://andriicf-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        enabled: false
      ingressUrl: http://host.docker.internal:8080
      name: test01
      isConfigurationRuntime: true
  installer:
    skipUsageValidation: true
    skipValidation: true
  internal-router:
    service:
      nodePort: 31243
      type: NodePort
  tunnel-client:
    enabled: false
