apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: g-andrii-hosted
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  source:
    repoURL: https://github.com/andrii-codefresh/g-andrii-hosted.git
    path: resources
    targetRevision: HEAD
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
