apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local8-release
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/andrii-codefresh/codefresh-runtime_internal-shared-config.git
    targetRevision: HEAD
    path: resources/local8/chart
    helm:
      releaseName: local8-release
  destination:
    namespace: local8
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
